name: 'inception'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/data/mariadb"

configs:
  nginx_wordpress_config:
    file: ./requirements/nginx/configs/inception.conf

secrets:
  ssl_certificate:
    file: ./ssl/inception-ssl.cert
  ssl_key:
    file: ./ssl/inception-ssl.key

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
    image: "mariadb"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    restart: on-failure
  wordpress:
      container_name: "wordpress"
      build:
        context: ./requirements/wordpress
      image: "wordpress"
      volumes:
        - wordpress:/var/www/wordpress
      env_file:
        - .env
      environment:
        FTP_HOST: ftp
        WORDPRESS_REDIS_HOST: redis
        WORDPRESS_REDIS_PORT: 6379
      networks:
        - inception
      expose:
        - "9000"
      restart: on-failure
      depends_on:
        mariadb:
          condition: service_healthy
        redis:
          condition: service_healthy
        ftp:
          condition: service_healthy
  redis:
    build:
      context: ./requirements/bonus/redis
    image: "redis"
    container_name: "redis"
    networks:
      - inception
    expose:
      - "6379"
    restart: on-failure
  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: "adminer"
    container_name: "adminer"
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9600"
    restart: on-failure
  ftp:
    build:
      context: ./requirements/bonus/ftp
    image: "ftp"
    container_name: "ftp"
    environment:
      - FTP_HOME=/home/wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/home/wordpress:rw
    expose:
      - "21"
    restart: on-failure
  website:
    build:
      context: ./requirements/bonus/website
    image: website
    container_name: "website"
    networks:
      - inception
    expose:
      - "3000"
    restart: on-failure
  yt-dlp:
    build:
      context: ./requirements/bonus/yt-dlp
    image: yt-dlp
    container_name: "yt-dlp"
    networks:
      - inception
    expose:
      - "8080"
    restart: on-failure
  nginx:
      build:
        context: ./requirements/nginx
      image: "nginx"
      container_name: "nginx"
      volumes:
        - wordpress:/var/www/wordpress
      configs:
        - source: nginx_wordpress_config
          target: /etc/nginx/sites-enabled/default
      secrets:
        - ssl_certificate
        - ssl_key
      networks:
        - inception
      ports:
        - "443:443"
      restart: on-failure
      depends_on:
        wordpress:
          condition: service_healthy
        adminer:
          condition: service_healthy