FROM debian:bookworm-slim

LABEL ma.1337.author="zmoumen <zmoumen@student.1337.ma>"
LABEL ma.1337.version="inception"


ADD https://github.com/static-web-server/static-web-server/releases/download/v2.24.2/static-web-server-v2.24.2-x86_64-unknown-linux-gnu.tar.gz /tmp

RUN tar -xvf /tmp/static-web-server-v2.24.2-x86_64-unknown-linux-gnu.tar.gz -C /tmp && \
    mv /tmp/static-web-server-v2.24.2-x86_64-unknown-linux-gnu/static-web-server /usr/local/bin && \
    rm -rf /tmp/static-web-server-v2.24.2-x86_64-unknown-linux-gnu
COPY portfolio /portfolio

HEALTHCHECK --start-period=10s --timeout=10s --interval=10s --retries=3 CMD ["pidof", "static-web-server"]

WORKDIR /portfolio
ENTRYPOINT ["static-web-server", "--port", "3000", "--root", "/portfolio"]
EXPOSE 3000