FROM debian:bookworm

LABEL name="ftp"
LABEL ma.1337.author="zmoumen <zmoumen@student.1337.ma>"
LABEL ma.1337.version="inception"

RUN apt update

RUN apt install -y vsftpd

COPY ./setup.sh spinup.sh /
RUN chmod +x /setup.sh /spinup.sh

RUN /setup.sh

HEALTHCHECK --start-period=10s --timeout=10s --interval=10s --retries=3 CMD ["pidof", "vsftpd"]

ENTRYPOINT ["/spinup.sh"]
CMD ["vsftpd", "/etc/vsftpd.conf"]
EXPOSE 21