FROM debian:bookworm


RUN apt update
RUN apt install -y redis-server

HEALTHCHECK --start-period=15s --timeout=10s --interval=10s --retries=3 CMD ["redis-cli", "ping"]

ENTRYPOINT ["redis-server", "--protected-mode", "no"]
EXPOSE 6379